### ISSUE TITLE
Attribute not exist error

### ISSUE THREAD

**Issue by aimchina** [arogachev/yii2-excel#11]
Error when preparing data for import: sheet "Tests", cell "A1". Attribute not exist.

**Comment by arogachev** [comment]
Please show your config and excel file.

**Comment by aimchina** [comment]
$importer = new Importer([
		
			'filePath' => Yii::getAlias('@backend/web/upload/234.xlsx'),
			
			'standardModelsConfig' => [
				[
					'className' => ShipIng::className(),
					'standardAttributesConfig' => [
						[
							'name' => 'ship_id',
							'valueReplacement' => function ($value) {
								return $value;
							},
						],
							
						[
							'name' => 'tender_id',
							'valueReplacement' => function ($value) {
								return $value ? Html::tag('p', $value) : '';
							},
						],
							
						[
							'name' => 'company_id',
							'valueReplacement' => function ($value) {
								return $value;
							},
						],
					],
				],
			],
		]);

**Comment by aimchina** [comment]
![1](https://cloud.githubusercontent.com/assets/11752702/8180741/c54160c8-1452-11e5-9221-9aed6993638d.png)

**Comment by aimchina** [comment]
please as soon as reply

**Comment by arogachev** [comment]
Make sure there are no redundant spaces and line breaks in attribute names in Excel file.

Current standard attributes config doesn't make sense, you need to modify it according to your model..

The component is designed for user friendly filling, it's better to write actuak company names instead of ids.

**Comment by arogachev** [comment]
Did my answer helped?

**Comment by arogachev** [comment]
I'm closing this because of missing feedback. Reopen if it's necessary.

**Comment by j1myx** [comment]
Hi, I just had the same problem, so I proceeded to debug the library and managed to find the call to that exception; In this way I realized that in order not to fall in it the cabacera of the xlsx file must be equal to that of the attributeLabels of the model. :D
