### ISSUE TITLE
when I import, throw this exception

### ISSUE THREAD

**Issue by Liv1020** [arogachev/yii2-excel#15]
Model label must be declared before attribute names or values

**Comment by arogachev** [comment]
Please show your Excel file content and config.

**Comment by Liv1020** [comment]
as same as your config, model is creat by myself

**Comment by arogachev** [comment]
If you use your own model, the config can't be the same. You neet adjust it according to your model features. Please show Excel file so I can advice on how to correct it.

**Comment by Liv1020** [comment]
![image](https://cloud.githubusercontent.com/assets/5382358/8633457/c1a7a6ae-27fb-11e5-9f6b-cbf05430db7e.png)
this is my model

![image](https://cloud.githubusercontent.com/assets/5382358/8633458/ea42939e-27fb-11e5-8a87-93b246378178.png)

**Comment by Liv1020** [comment]
this is my config

![image](https://cloud.githubusercontent.com/assets/5382358/8633460/0aaca34a-27fc-11e5-91a0-2ec6dfcabccc.png)

**Comment by Liv1020** [comment]
can you look this bug??

**Comment by arogachev** [comment]
You just copied it from README. It's mentioned only for example. You need to correct it according to your model. Also check cell formatting. Could you provide an example of what you want to import?

**Comment by Liv1020** [comment]
![image](https://cloud.githubusercontent.com/assets/5382358/8637468/e827706a-28c4-11e5-9f65-1c4c7ff1f9d8.png)
I want import this

**Comment by Liv1020** [comment]
can you help me?

**Comment by arogachev** [comment]
Formatting for attribute names is missing, By default it should be written in *italics* font. See examples in README.
