### ISSUE TITLE
Out of memory.

### ISSUE THREAD

**Issue by ignatenkovnikita** [arogachev/yii2-excel#29]
I run import and get error.
`PHP Fatal Error 'yii\base\ErrorException' with message 'Out of memory (allocated 1533804544)`

**Comment by arogachev** [comment]
Where the error happens? On local or production server? How big the excel file is?

**Comment by ignatenkovnikita** [comment]
File excel is 1 Mb.
Structure
string | string
asdfs | sdfsd

On local and production server has error.
Server has 2Gb ram and 2Gb swap.

**Comment by arogachev** [comment]
@ignatenkovnikita Could you share this file?

**Comment by ignatenkovnikita** [comment]
https://www.dropbox.com/s/ee4j7rvhja68n7s/example.xlsx?dl=0

**Comment by arogachev** [comment]
Отвечу на русском.

1) Файл слишком большой для импорта. Я даже не смог открыть его по указанной ссылке (браузер зависает). Если есть возможность, меняйте настройки времени исполнения и памяти:

```php
set_time_limit(0);
ini_set('memory_limit', '-1');
```

Дополнительно может потребоваться изменения настроек веб-сервера, если будет 504 ошибка.

В качестве альтернативы можно использовать очередь и выполнять в cli, а не через веб интерфейс.

Большое потребление памяти также обусловлено особенностями работы PHPExcel. Можно разбить файл на несколько частей поменьше и импортировать уже их поочередно.

2) Использование расширения при такой структуре данных вряд ли имеет смысл, то же самое можно сделать, сохранив в csv и используя встроенные функции БД по импорту из CSV.

**Comment by ignatenkovnikita** [comment]
Спасибо.

1) Запуск  был через cli)
2) ну в целом так и было сделано, разбил на несколько файлов по 1Мб и все заработало.
Спасибо!
