### ISSUE TITLE
Insert additional column that not in excel file

### ISSUE THREAD

**Issue by waisan** [arogachev/yii2-excel#41]
Hi,

how can I add in the additional column that are not in the excel file?
in my excel file =>  | id | name | description |
when import, I wanna have another attribute called 'created_at' and assign current date to this field.
how can I achieve this? 

Thanks if anyone can help.

**Comment by arogachev** [comment]
There are 2 main options:

- Handle it on database side with correct definition of table's column. This can vary depending on used RDBMS. Here is an [example for MySQL].
- Use framework's tools. Yii2 has a special behavior exactly for these purposes, it's called [TimestampBehavior].

[example for MySQL]: https://dev.mysql.com/doc/refman/5.5/en/timestamp-initialization.html
[TimestampBehavior]: http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html
