### ISSUE TITLE
Error when preparing data for import: sheet "Parents", cell "A2". Attribute not exist.

### ISSUE THREAD

**Issue by zizango123** [arogachev/yii2-excel#42]
When i try to import data from excel sheet to db using yii2 and this plugin the following error shows up . I need help 

"Error when preparing data for import: sheet "Parents", cell "A2". Attribute not exist."

**Comment by arogachev** [comment]
@zizango123 The error is clear - you specified non-existing attribute name for model. For further help, please provide more details - the structure of models, used config for import and relevant piece of data from Excel (you can replace / remove sensitive information).

**Comment by zizango123** [comment]
Everything Works fine now. I was using the database attribute names instead of the assigned attribute labels.
